language: ruby
cache: bundler
rvm:
  - 2.5
services:
  - redis-server
env:
  - REGION=EU
before_script:
  - bundle install --without development --deployment --retry=3 --jobs=3
script:
  - bundle exec bundle-audit check --update
  - bundle exec rspec --format documentation
